--region was missing in multiple aws ec2 commands

diff --git a/aws_start.sh.patch b/aws_start.sh.patch
--- a/aws_start.sh.patch
+++ b/aws_start.sh.patch
@@ -1,5 +1,5 @@
 --- startup/aws_start.sh	2024-06-06 17:39:40.000000000 -0700
-+++ startup/aws_start.sh	2024-06-06 19:57:38.095215423 -0700
++++ startup/aws_start.sh	2024-06-10 10:25:02.256780186 -0700
 @@ -87,7 +87,7 @@
    EC2_TYPE=t2.xlarge
    REGION=us-west-2
@@ -20,11 +20,46 @@
      prompt ans "region = ${REGION}, ami image = ${AMI_IMAGE}, EC2 type = ${EC2_TYPE}, OK? (Y/n) "
      if [[ $ans = "" ]] || [[ $ans =~ ^(y|Y)$ ]]
      then
-@@ -175,11 +175,19 @@
+@@ -146,9 +146,9 @@
+ 
+ echo "Generating key pair for VM"
+ 
+-aws ec2 delete-key-pair --key-name $KEY_PAIR > /dev/null 2>&1
++aws ec2 delete-key-pair --region $REGION --key-name $KEY_PAIR > /dev/null 2>&1
+ rm -rf $KEY_FILE
+-aws ec2 create-key-pair --key-name $KEY_PAIR --query 'KeyMaterial' --output text > $KEY_FILE
++aws ec2 create-key-pair --region $REGION --key-name $KEY_PAIR --query 'KeyMaterial' --output text > $KEY_FILE
+ report_status "$?" "creating key pair"
+ chmod 400 $KEY_FILE
+ 
+@@ -156,18 +156,18 @@
+ # Try not reusing existing security group because we have to modify it for our own need.
+ if [ $using_default_vpc == true ]
+ then
+-  sg_id=$(aws ec2 create-security-group --group-name $SECURITY_GROUP --description "NVFlare security group" | jq -r .GroupId)
++  sg_id=$(aws ec2 create-security-group --region $REGION --group-name $SECURITY_GROUP --description "NVFlare security group" | jq -r .GroupId)
+ else
+-  sg_id=$(aws ec2 create-security-group --group-name $SECURITY_GROUP --description "NVFlare security group" --vpc-id $vpc_id | jq -r .GroupId)
++  sg_id=$(aws ec2 create-security-group --region $REGION --group-name $SECURITY_GROUP --description "NVFlare security group" --vpc-id $vpc_id | jq -r .GroupId)
+ fi
+ report_status "$?" "creating security group"
+ my_public_ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
+ if [ "$?" -eq 0 ] && [[ "$my_public_ip" =~ ^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$ ]]
+ then
+-  aws ec2 authorize-security-group-ingress --group-id $sg_id --protocol tcp --port 22 --cidr ${my_public_ip}/32 > /tmp/sec_grp.log
++  aws ec2 authorize-security-group-ingress --region $REGION --group-id $sg_id --protocol tcp --port 22 --cidr ${my_public_ip}/32 > /tmp/sec_grp.log
+ else
+   echo "getting my public IP failed, please manually configure the inbound rule to limit SSH access"
+-  aws ec2 authorize-security-group-ingress --group-id $sg_id --protocol tcp --port 22 --cidr 0.0.0.0/0 > /tmp/sec_grp.log
++  aws ec2 authorize-security-group-ingress --region $REGION --group-id $sg_id --protocol tcp --port 22 --cidr 0.0.0.0/0 > /tmp/sec_grp.log
+ fi
+ report_status "$?" "creating security group rules"
+ 
+@@ -175,17 +175,25 @@
  
  echo "Creating VM at region $REGION, may take a few minutes."
  
-+ ami_info=$(aws ec2 describe-images --image-ids $AMI_IMAGE --output json)
++ ami_info=$(aws ec2 describe-images --region $REGION --image-ids $AMI_IMAGE --output json)
 + amidevice=$(echo $ami_info | jq -r '.Images[0].BlockDeviceMappings[0].DeviceName')
 + block_device_mappings=$(echo $ami_info | jq -r '.Images[0].BlockDeviceMappings')
 + original_size=$(echo $block_device_mappings | jq -r '.[0].Ebs.VolumeSize')
@@ -42,6 +77,14 @@
  fi
  report_status "$?" "creating VM"
  instance_id=$(jq -r .Instances[0].InstanceId vm_create.json)
+ 
+-aws ec2 wait instance-status-ok --instance-ids $instance_id
+-aws ec2 describe-instances --instance-ids $instance_id > vm_result.json
++aws ec2 wait instance-status-ok --region $REGION --instance-ids $instance_id
++aws ec2 describe-instances --region $REGION --instance-ids $instance_id > vm_result.json
+ 
+ IP_ADDRESS=$(jq -r .Reservations[0].Instances[0].PublicIpAddress vm_result.json)
+ 
 @@ -209,10 +217,16 @@
  else
    echo "Installing packages in $VM_NAME, may take a few minutes."
@@ -62,3 +105,9 @@
    nohup ${DEST_FOLDER}/startup/start.sh && sleep 20 && \
    exit" > /tmp/nvflare.log 2>&1 
  
+@@ -225,3 +239,5 @@
+ echo "Other resources provisioned"
+ echo "security group: ${SECURITY_GROUP}"
+ echo "key pair: ${KEY_PAIR}"
++echo "login: ssh -i ${KEY_PAIR}.pem ubuntu@${IP_ADDRESS}"
+
